// Whitelist arrays - ALL routes must be generated from these

export const INGREDIENTS = [
  // Original ingredients (keeping for compatibility)
  'flour',
  'sugar',
  'brown-sugar',
  'butter',
  'milk',
  'water',
  'honey',
  'olive-oil',
  'rice',
  'salt',
  'baking-powder',
  'cocoa-powder',
  'oats',
  'yogurt',
  'cream',
  'chopped-onion',
  'shredded-cheese',
  'breadcrumbs',
  'peanut-butter',
  'jam',
  
  // Flours and Starches
  'almond-flour',
  'coconut-flour',
  'whole-wheat-flour',
  'self-rising-flour',
  'bread-flour',
  'cake-flour',
  'cornstarch',
  'cornmeal',
  'tapioca-flour',
  'rice-flour',
  'potato-starch',
  'arrowroot-powder',
  
  // Sugars and Sweeteners
  'powdered-sugar',
  'granulated-sugar',
  'icing-sugar',
  'confectioners-sugar',
  'maple-syrup',
  'agave-syrup',
  'molasses',
  'corn-syrup',
  'golden-syrup',
  'stevia',
  'coconut-sugar',
  'turbinado-sugar',
  'raw-sugar',
  
  // Dairy Products
  'heavy-cream',
  'sour-cream',
  'greek-yogurt',
  'cream-cheese',
  'mascarpone',
  'ricotta-cheese',
  'cottage-cheese',
  'buttermilk',
  'evaporated-milk',
  'condensed-milk',
  'half-and-half',
  'whipping-cream',
  'goat-cheese',
  'feta-cheese',
  'mozzarella',
  'parmesan',
  'cheddar-cheese',
  'swiss-cheese',
  'gouda',
  'brie',
  'blue-cheese',
  
  // Oils and Fats
  'canola-oil',
  'vegetable-oil',
  'avocado-oil',
  'sesame-oil',
  'coconut-oil',
  'sunflower-oil',
  'grapeseed-oil',
  'walnut-oil',
  'flaxseed-oil',
  'lard',
  'shortening',
  'margarine',
  'ghee',
  'clarified-butter',
  'salted-butter',
  'unsalted-butter',
  
  // Eggs
  'egg-large',
  'egg-white',
  'egg-yolk',
  'whole-egg',
  
  // Grains and Legumes
  'brown-rice',
  'wild-rice',
  'jasmine-rice',
  'basmati-rice',
  'quinoa',
  'barley',
  'lentils',
  'chickpeas',
  'black-beans',
  'kidney-beans',
  'pinto-beans',
  'navy-beans',
  'cannellini-beans',
  'split-peas',
  'bulgur',
  'couscous',
  'farro',
  'millet',
  'buckwheat',
  
  // Nuts and Seeds
  'almonds',
  'walnuts',
  'pecans',
  'cashews',
  'hazelnuts',
  'pistachios',
  'macadamia-nuts',
  'pine-nuts',
  'chia-seeds',
  'flax-seeds',
  'sunflower-seeds',
  'pumpkin-seeds',
  'sesame-seeds',
  'poppy-seeds',
  'hemp-seeds',
  
  // Chocolate and Cocoa
  'dark-chocolate',
  'milk-chocolate',
  'white-chocolate',
  'chocolate-chips',
  'cocoa-powder-dutch',
  'cacao-powder',
  'chocolate-shavings',
  
  // Fruits (Fresh and Dried)
  'banana-mashed',
  'applesauce',
  'dried-cranberries',
  'raisins',
  'dates',
  'prunes',
  'dried-apricots',
  'dried-figs',
  'coconut-shredded',
  'coconut-flakes',
  
  // Vegetables
  'carrots-chopped',
  'celery-chopped',
  'bell-pepper-chopped',
  'mushrooms-chopped',
  'spinach',
  'kale',
  'broccoli-chopped',
  'cauliflower-chopped',
  'zucchini-chopped',
  'cucumber-chopped',
  'tomatoes-diced',
  'garlic-minced',
  'ginger-minced',
  
  // Tomato Products
  'tomato-paste',
  'tomato-sauce',
  'tomato-puree',
  'ketchup',
  'crushed-tomatoes',
  'diced-tomatoes',
  
  // Condiments and Sauces
  'vinegar',
  'apple-cider-vinegar',
  'balsamic-vinegar',
  'white-vinegar',
  'rice-vinegar',
  'soy-sauce',
  'worcestershire-sauce',
  'hot-sauce',
  'mustard',
  'mayonnaise',
  'sriracha',
  'hoisin-sauce',
  'teriyaki-sauce',
  
  // Broths and Stocks
  'chicken-broth',
  'beef-broth',
  'vegetable-broth',
  'bone-broth',
  'fish-stock',
  
  // Spices and Seasonings
  'black-pepper',
  'cayenne-pepper',
  'paprika',
  'cumin',
  'coriander',
  'turmeric',
  'cinnamon',
  'nutmeg',
  'allspice',
  'cloves',
  'cardamom',
  'ginger-powder',
  'garlic-powder',
  'onion-powder',
  'chili-powder',
  'curry-powder',
  'italian-seasoning',
  'herbs-de-provence',
  
  // Baking Ingredients
  'baking-soda',
  'yeast',
  'vanilla-extract',
  'almond-extract',
  'lemon-zest',
  'orange-zest',
  'cream-of-tartar',
  'corn-syrup-light',
  'corn-syrup-dark',
  
  // Oats Varieties
  'rolled-oats',
  'instant-oats',
  'steel-cut-oats',
  'quick-oats',
  
  // Additional Common Ingredients
  'tahini',
  'hummus',
  'pesto',
  'salsa',
  'guacamole',
  'ranch-dressing',
  'italian-dressing',
  'vinaigrette',
] as const;

export const INGREDIENT_CONVERTERS = [
  'cups-to-grams',
  'grams-to-cups',
  'tbsp-to-grams',
] as const;

export const PURE_PAGES = [
  'cups-to-ml',
  'ml-to-cups',
  'oz-to-grams',
  'grams-to-oz',
  'tbsp-to-ml',
  'tsp-to-ml',
] as const;

// Ingredient densities (grams per cup)
export const INGREDIENT_DENSITIES: Record<string, number> = {
  // Original ingredients
  'flour': 120,
  'sugar': 200,
  'brown-sugar': 220,
  'butter': 227,
  'milk': 240,
  'water': 236,
  'honey': 340,
  'olive-oil': 215,
  'rice': 185,
  'salt': 288,
  'baking-powder': 192,
  'cocoa-powder': 100,
  'oats': 90,
  'yogurt': 245,
  'cream': 240,
  'chopped-onion': 160,
  'shredded-cheese': 110,
  'breadcrumbs': 120,
  'peanut-butter': 270,
  'jam': 320,
  
  // Flours and Starches
  'almond-flour': 96,
  'coconut-flour': 112,
  'whole-wheat-flour': 130,
  'self-rising-flour': 125,
  'bread-flour': 127,
  'cake-flour': 115,
  'cornstarch': 128,
  'cornmeal': 122,
  'tapioca-flour': 120,
  'rice-flour': 158,
  'potato-starch': 192,
  'arrowroot-powder': 128,
  
  // Sugars and Sweeteners
  'powdered-sugar': 120,
  'granulated-sugar': 200,
  'icing-sugar': 120,
  'confectioners-sugar': 120,
  'maple-syrup': 322,
  'agave-syrup': 340,
  'molasses': 337,
  'corn-syrup': 328,
  'golden-syrup': 340,
  'stevia': 1,
  'coconut-sugar': 200,
  'turbinado-sugar': 200,
  'raw-sugar': 200,
  
  // Dairy Products
  'heavy-cream': 238,
  'sour-cream': 240,
  'greek-yogurt': 285,
  'cream-cheese': 232,
  'mascarpone': 250,
  'ricotta-cheese': 246,
  'cottage-cheese': 226,
  'buttermilk': 245,
  'evaporated-milk': 252,
  'condensed-milk': 306,
  'half-and-half': 242,
  'whipping-cream': 238,
  'goat-cheese': 150,
  'feta-cheese': 150,
  'mozzarella': 113,
  'parmesan': 100,
  'cheddar-cheese': 113,
  'swiss-cheese': 108,
  'gouda': 113,
  'brie': 140,
  'blue-cheese': 150,
  
  // Oils and Fats
  'canola-oil': 218,
  'vegetable-oil': 218,
  'avocado-oil': 218,
  'sesame-oil': 218,
  'coconut-oil': 218,
  'sunflower-oil': 218,
  'grapeseed-oil': 218,
  'walnut-oil': 218,
  'flaxseed-oil': 218,
  'lard': 205,
  'shortening': 192,
  'margarine': 227,
  'ghee': 227,
  'clarified-butter': 227,
  'salted-butter': 227,
  'unsalted-butter': 227,
  
  // Eggs
  'egg-large': 243,
  'egg-white': 240,
  'egg-yolk': 243,
  'whole-egg': 243,
  
  // Grains and Legumes
  'brown-rice': 195,
  'wild-rice': 164,
  'jasmine-rice': 185,
  'basmati-rice': 185,
  'quinoa': 185,
  'barley': 200,
  'lentils': 192,
  'chickpeas': 200,
  'black-beans': 194,
  'kidney-beans': 184,
  'pinto-beans': 193,
  'navy-beans': 192,
  'cannellini-beans': 190,
  'split-peas': 196,
  'bulgur': 182,
  'couscous': 173,
  'farro': 200,
  'millet': 200,
  'buckwheat': 170,
  
  // Nuts and Seeds
  'almonds': 143,
  'walnuts': 120,
  'pecans': 109,
  'cashews': 137,
  'hazelnuts': 135,
  'pistachios': 123,
  'macadamia-nuts': 134,
  'pine-nuts': 135,
  'chia-seeds': 168,
  'flax-seeds': 168,
  'sunflower-seeds': 144,
  'pumpkin-seeds': 129,
  'sesame-seeds': 144,
  'poppy-seeds': 144,
  'hemp-seeds': 168,
  
  // Chocolate and Cocoa
  'dark-chocolate': 170,
  'milk-chocolate': 175,
  'white-chocolate': 170,
  'chocolate-chips': 170,
  'cocoa-powder-dutch': 100,
  'cacao-powder': 100,
  'chocolate-shavings': 100,
  
  // Fruits (Fresh and Dried)
  'banana-mashed': 240,
  'applesauce': 255,
  'dried-cranberries': 120,
  'raisins': 165,
  'dates': 178,
  'prunes': 174,
  'dried-apricots': 130,
  'dried-figs': 149,
  'coconut-shredded': 80,
  'coconut-flakes': 80,
  
  // Vegetables
  'carrots-chopped': 128,
  'celery-chopped': 100,
  'bell-pepper-chopped': 149,
  'mushrooms-chopped': 70,
  'spinach': 30,
  'kale': 67,
  'broccoli-chopped': 91,
  'cauliflower-chopped': 107,
  'zucchini-chopped': 124,
  'cucumber-chopped': 119,
  'tomatoes-diced': 180,
  'garlic-minced': 136,
  'ginger-minced': 96,
  
  // Tomato Products
  'tomato-paste': 262,
  'tomato-sauce': 245,
  'tomato-puree': 245,
  'ketchup': 272,
  'crushed-tomatoes': 240,
  'diced-tomatoes': 240,
  
  // Condiments and Sauces
  'vinegar': 239,
  'apple-cider-vinegar': 239,
  'balsamic-vinegar': 272,
  'white-vinegar': 239,
  'rice-vinegar': 239,
  'soy-sauce': 255,
  'worcestershire-sauce': 255,
  'hot-sauce': 240,
  'mustard': 249,
  'mayonnaise': 220,
  'sriracha': 240,
  'hoisin-sauce': 280,
  'teriyaki-sauce': 255,
  
  // Broths and Stocks
  'chicken-broth': 240,
  'beef-broth': 240,
  'vegetable-broth': 240,
  'bone-broth': 240,
  'fish-stock': 240,
  
  // Spices and Seasonings
  'black-pepper': 230,
  'cayenne-pepper': 230,
  'paprika': 108,
  'cumin': 120,
  'coriander': 80,
  'turmeric': 120,
  'cinnamon': 120,
  'nutmeg': 120,
  'allspice': 120,
  'cloves': 120,
  'cardamom': 120,
  'ginger-powder': 120,
  'garlic-powder': 150,
  'onion-powder': 150,
  'chili-powder': 120,
  'curry-powder': 120,
  'italian-seasoning': 80,
  'herbs-de-provence': 80,
  
  // Baking Ingredients
  'baking-soda': 220,
  'yeast': 144,
  'vanilla-extract': 208,
  'almond-extract': 208,
  'lemon-zest': 96,
  'orange-zest': 96,
  'cream-of-tartar': 200,
  'corn-syrup-light': 328,
  'corn-syrup-dark': 328,
  
  // Oats Varieties
  'rolled-oats': 90,
  'instant-oats': 90,
  'steel-cut-oats': 180,
  'quick-oats': 90,
  
  // Additional Common Ingredients
  'tahini': 256,
  'hummus': 246,
  'pesto': 239,
  'salsa': 256,
  'guacamole': 246,
  'ranch-dressing': 240,
  'italian-dressing': 240,
  'vinaigrette': 240,
};

// Ingredient display names
export const INGREDIENT_NAMES: Record<string, string> = {
  // Original ingredients
  'flour': 'Flour',
  'sugar': 'Sugar',
  'brown-sugar': 'Brown Sugar',
  'butter': 'Butter',
  'milk': 'Milk',
  'water': 'Water',
  'honey': 'Honey',
  'olive-oil': 'Olive Oil',
  'rice': 'Rice',
  'salt': 'Salt',
  'baking-powder': 'Baking Powder',
  'cocoa-powder': 'Cocoa Powder',
  'oats': 'Oats',
  'yogurt': 'Yogurt',
  'cream': 'Cream',
  'chopped-onion': 'Chopped Onion',
  'shredded-cheese': 'Shredded Cheese',
  'breadcrumbs': 'Breadcrumbs',
  'peanut-butter': 'Peanut Butter',
  'jam': 'Jam',
  
  // Flours and Starches
  'almond-flour': 'Almond Flour',
  'coconut-flour': 'Coconut Flour',
  'whole-wheat-flour': 'Whole Wheat Flour',
  'self-rising-flour': 'Self-Rising Flour',
  'bread-flour': 'Bread Flour',
  'cake-flour': 'Cake Flour',
  'cornstarch': 'Cornstarch',
  'cornmeal': 'Cornmeal',
  'tapioca-flour': 'Tapioca Flour',
  'rice-flour': 'Rice Flour',
  'potato-starch': 'Potato Starch',
  'arrowroot-powder': 'Arrowroot Powder',
  
  // Sugars and Sweeteners
  'powdered-sugar': 'Powdered Sugar',
  'granulated-sugar': 'Granulated Sugar',
  'icing-sugar': 'Icing Sugar',
  'confectioners-sugar': 'Confectioners Sugar',
  'maple-syrup': 'Maple Syrup',
  'agave-syrup': 'Agave Syrup',
  'molasses': 'Molasses',
  'corn-syrup': 'Corn Syrup',
  'golden-syrup': 'Golden Syrup',
  'stevia': 'Stevia',
  'coconut-sugar': 'Coconut Sugar',
  'turbinado-sugar': 'Turbinado Sugar',
  'raw-sugar': 'Raw Sugar',
  
  // Dairy Products
  'heavy-cream': 'Heavy Cream',
  'sour-cream': 'Sour Cream',
  'greek-yogurt': 'Greek Yogurt',
  'cream-cheese': 'Cream Cheese',
  'mascarpone': 'Mascarpone',
  'ricotta-cheese': 'Ricotta Cheese',
  'cottage-cheese': 'Cottage Cheese',
  'buttermilk': 'Buttermilk',
  'evaporated-milk': 'Evaporated Milk',
  'condensed-milk': 'Condensed Milk',
  'half-and-half': 'Half and Half',
  'whipping-cream': 'Whipping Cream',
  'goat-cheese': 'Goat Cheese',
  'feta-cheese': 'Feta Cheese',
  'mozzarella': 'Mozzarella',
  'parmesan': 'Parmesan',
  'cheddar-cheese': 'Cheddar Cheese',
  'swiss-cheese': 'Swiss Cheese',
  'gouda': 'Gouda',
  'brie': 'Brie',
  'blue-cheese': 'Blue Cheese',
  
  // Oils and Fats
  'canola-oil': 'Canola Oil',
  'vegetable-oil': 'Vegetable Oil',
  'avocado-oil': 'Avocado Oil',
  'sesame-oil': 'Sesame Oil',
  'coconut-oil': 'Coconut Oil',
  'sunflower-oil': 'Sunflower Oil',
  'grapeseed-oil': 'Grapeseed Oil',
  'walnut-oil': 'Walnut Oil',
  'flaxseed-oil': 'Flaxseed Oil',
  'lard': 'Lard',
  'shortening': 'Shortening',
  'margarine': 'Margarine',
  'ghee': 'Ghee',
  'clarified-butter': 'Clarified Butter',
  'salted-butter': 'Salted Butter',
  'unsalted-butter': 'Unsalted Butter',
  
  // Eggs
  'egg-large': 'Egg (Large)',
  'egg-white': 'Egg White',
  'egg-yolk': 'Egg Yolk',
  'whole-egg': 'Whole Egg',
  
  // Grains and Legumes
  'brown-rice': 'Brown Rice',
  'wild-rice': 'Wild Rice',
  'jasmine-rice': 'Jasmine Rice',
  'basmati-rice': 'Basmati Rice',
  'quinoa': 'Quinoa',
  'barley': 'Barley',
  'lentils': 'Lentils',
  'chickpeas': 'Chickpeas',
  'black-beans': 'Black Beans',
  'kidney-beans': 'Kidney Beans',
  'pinto-beans': 'Pinto Beans',
  'navy-beans': 'Navy Beans',
  'cannellini-beans': 'Cannellini Beans',
  'split-peas': 'Split Peas',
  'bulgur': 'Bulgur',
  'couscous': 'Couscous',
  'farro': 'Farro',
  'millet': 'Millet',
  'buckwheat': 'Buckwheat',
  
  // Nuts and Seeds
  'almonds': 'Almonds',
  'walnuts': 'Walnuts',
  'pecans': 'Pecans',
  'cashews': 'Cashews',
  'hazelnuts': 'Hazelnuts',
  'pistachios': 'Pistachios',
  'macadamia-nuts': 'Macadamia Nuts',
  'pine-nuts': 'Pine Nuts',
  'chia-seeds': 'Chia Seeds',
  'flax-seeds': 'Flax Seeds',
  'sunflower-seeds': 'Sunflower Seeds',
  'pumpkin-seeds': 'Pumpkin Seeds',
  'sesame-seeds': 'Sesame Seeds',
  'poppy-seeds': 'Poppy Seeds',
  'hemp-seeds': 'Hemp Seeds',
  
  // Chocolate and Cocoa
  'dark-chocolate': 'Dark Chocolate',
  'milk-chocolate': 'Milk Chocolate',
  'white-chocolate': 'White Chocolate',
  'chocolate-chips': 'Chocolate Chips',
  'cocoa-powder-dutch': 'Cocoa Powder (Dutch Process)',
  'cacao-powder': 'Cacao Powder',
  'chocolate-shavings': 'Chocolate Shavings',
  
  // Fruits (Fresh and Dried)
  'banana-mashed': 'Banana (Mashed)',
  'applesauce': 'Applesauce',
  'dried-cranberries': 'Dried Cranberries',
  'raisins': 'Raisins',
  'dates': 'Dates',
  'prunes': 'Prunes',
  'dried-apricots': 'Dried Apricots',
  'dried-figs': 'Dried Figs',
  'coconut-shredded': 'Shredded Coconut',
  'coconut-flakes': 'Coconut Flakes',
  
  // Vegetables
  'carrots-chopped': 'Carrots (Chopped)',
  'celery-chopped': 'Celery (Chopped)',
  'bell-pepper-chopped': 'Bell Pepper (Chopped)',
  'mushrooms-chopped': 'Mushrooms (Chopped)',
  'spinach': 'Spinach',
  'kale': 'Kale',
  'broccoli-chopped': 'Broccoli (Chopped)',
  'cauliflower-chopped': 'Cauliflower (Chopped)',
  'zucchini-chopped': 'Zucchini (Chopped)',
  'cucumber-chopped': 'Cucumber (Chopped)',
  'tomatoes-diced': 'Tomatoes (Diced)',
  'garlic-minced': 'Garlic (Minced)',
  'ginger-minced': 'Ginger (Minced)',
  
  // Tomato Products
  'tomato-paste': 'Tomato Paste',
  'tomato-sauce': 'Tomato Sauce',
  'tomato-puree': 'Tomato Puree',
  'ketchup': 'Ketchup',
  'crushed-tomatoes': 'Crushed Tomatoes',
  'diced-tomatoes': 'Diced Tomatoes',
  
  // Condiments and Sauces
  'vinegar': 'Vinegar',
  'apple-cider-vinegar': 'Apple Cider Vinegar',
  'balsamic-vinegar': 'Balsamic Vinegar',
  'white-vinegar': 'White Vinegar',
  'rice-vinegar': 'Rice Vinegar',
  'soy-sauce': 'Soy Sauce',
  'worcestershire-sauce': 'Worcestershire Sauce',
  'hot-sauce': 'Hot Sauce',
  'mustard': 'Mustard',
  'mayonnaise': 'Mayonnaise',
  'sriracha': 'Sriracha',
  'hoisin-sauce': 'Hoisin Sauce',
  'teriyaki-sauce': 'Teriyaki Sauce',
  
  // Broths and Stocks
  'chicken-broth': 'Chicken Broth',
  'beef-broth': 'Beef Broth',
  'vegetable-broth': 'Vegetable Broth',
  'bone-broth': 'Bone Broth',
  'fish-stock': 'Fish Stock',
  
  // Spices and Seasonings
  'black-pepper': 'Black Pepper',
  'cayenne-pepper': 'Cayenne Pepper',
  'paprika': 'Paprika',
  'cumin': 'Cumin',
  'coriander': 'Coriander',
  'turmeric': 'Turmeric',
  'cinnamon': 'Cinnamon',
  'nutmeg': 'Nutmeg',
  'allspice': 'Allspice',
  'cloves': 'Cloves',
  'cardamom': 'Cardamom',
  'ginger-powder': 'Ginger Powder',
  'garlic-powder': 'Garlic Powder',
  'onion-powder': 'Onion Powder',
  'chili-powder': 'Chili Powder',
  'curry-powder': 'Curry Powder',
  'italian-seasoning': 'Italian Seasoning',
  'herbs-de-provence': 'Herbs de Provence',
  
  // Baking Ingredients
  'baking-soda': 'Baking Soda',
  'yeast': 'Yeast',
  'vanilla-extract': 'Vanilla Extract',
  'almond-extract': 'Almond Extract',
  'lemon-zest': 'Lemon Zest',
  'orange-zest': 'Orange Zest',
  'cream-of-tartar': 'Cream of Tartar',
  'corn-syrup-light': 'Corn Syrup (Light)',
  'corn-syrup-dark': 'Corn Syrup (Dark)',
  
  // Oats Varieties
  'rolled-oats': 'Rolled Oats',
  'instant-oats': 'Instant Oats',
  'steel-cut-oats': 'Steel Cut Oats',
  'quick-oats': 'Quick Oats',
  
  // Additional Common Ingredients
  'tahini': 'Tahini',
  'hummus': 'Hummus',
  'pesto': 'Pesto',
  'salsa': 'Salsa',
  'guacamole': 'Guacamole',
  'ranch-dressing': 'Ranch Dressing',
  'italian-dressing': 'Italian Dressing',
  'vinaigrette': 'Vinaigrette',
};

export type Ingredient = typeof INGREDIENTS[number];
export type IngredientConverter = typeof INGREDIENT_CONVERTERS[number];
export type PurePage = typeof PURE_PAGES[number];
